spring:
  application:
    name: Gateway-Service
  cloud:
    gateway:
      routes:
      - id: countries-service
        uri: lb://countries-service
        predicates:
        - Path=/country/**
        filters:
        - name: CircuitBreaker
        - args:
             name: country-service
             fallbackuri:  forward:/countryFallBack
             
      - id: capita-service
        uri: lb://capital-service
        predicates:
        - Path=/capital/**
        filters:
        - name: CircuitBreaker
        - args:
             name: capital-service
             fallbackuri: forward:/capitalFallBack
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8771/eureka
      
server:
  port: 8989      
      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
        
hystrix:
  command:
    fallbackcmd:
       execution:
         isolation:
            thread:
              timeoutInMilliseconds: 5000        
 
          
      
          